### PR TITLE
Packagist distribution

### PR DESCRIPTION
**Pull request by dmitrybelyakov**
Hi,

Here's a composer.json module manifest. With it in place you can have the module distributed through packagist and installable with composer.

It's pretty cool because it allows other modules to depend on this one.

Cheers and good luck,
Dmitry :)

### CODE REVIEW

**Comment by mtymek** [comment]
Why did you close that PR? :-) I was about to test it (didn't use composer before) and merge.

**Comment by dmitrybelyakov** [comment]
Guess we better get back to in 3 weeks when new view funcationality will be done since a lot might change :)

**Comment by dmitrybelyakov** [comment]
... I still do wonder how would you go about rendering forms with twig?

**Comment by mtymek** [comment]
Didn't try that one in ZF2. In my ZF1+Twig app I inject form to view:

```
$this->view->form =new Application_Form_Foo();
```

then I can either display full form:

```
{{ form | raw }} 
```

or separate elements:

```
{{ form.emailInput.renderViewHelper() | raw }}
{{ form.emailInput.renderViewHelper() | raw }}
```

I guess it would work very similar in ZF2.

**Comment by dmitrybelyakov** [comment]
Ok, seems like what I was looking for, thanks. So we wait untill new View layer comes with beta3 that might also include some changes to the forms component.

I have one suggestion regarding your module - it might be better not to bundle the twig itself within module and rely on packagist to load that as a dependency.

Dmitry.

**Comment by mtymek** [comment]
I'm looking forward for beta3, my plan is to make this module more robust then (hopefully I won't need custom view helper at that point, I'll add unit tests, etc.).
I'm not convinced yet what's the best way of managing dependencies. I feel that leaving Twig as a submodule is not so bad - user will be able to choose if he wants to use composer, or simple "git clone --recursive". I'll give it more thought when B3 is around.

**Comment by dmitrybelyakov** [comment]
Ok then. Ping me I can help you with tests and docs :)

**Comment by mtymek** [comment]
Thanks!

**Pull request closed without merging**
